services:
  fl-dev:
    user: "vscode"
    working_dir: /home/vscode/fl-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/home/vscode/fl-dev
      - fl-dev-venv:/home/vscode/fl-dev/.venv
    environment:
      - HOME=/home/vscode
      - UV_LINK_MODE=copy
    tty: true

volumes:
  fl-dev-venv:
